### PR TITLE
Unbreak Wayland build after Vulkan-Headers update

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by cb75c422e529 via KhronosGroup/Vulkan-Headers@5177b119bbdf: `<vulkan/vulkan.h>` no longer bootlegs `<wayland-client.h>`.

```c++
$ qmake-qt5 DEFINES+=WAYLAND && make
[...]
vulkancapsviewer.cpp:765:41: error: use of undeclared identifier 'wl_display_connect'
            surfaceCreateInfo.display = wl_display_connect(NULL);
                                        ^
```

### CODE REVIEW

**Comment by SaschaWillems** [comment]
Can you elaborate? Is this similar or the same as #155?

**Comment by jbeich** [comment]
Same as #154. I did try to preserve `#ifdef` order (Wayland then XCB) but it's purely cosmetic.
